import React, { useState } from "react";
import {
  AppstoreOutlined,
  TagOutlined,
  UserOutlined,
  TeamOutlined,
  DollarOutlined,
  RiseOutlined,
  SettingOutlined,
  SwapOutlined,
  DatabaseFilled,
  BankOutlined,
  HomeOutlined,
  NotificationOutlined,
} from "@ant-design/icons";

export const menuData = [
  {
    key: "/home",
    path: "/home",
    title: "Bảng điều khiển",
    icon: <HomeOutlined />,
    role: true,
    subs: [
      {
        key: "/analytics",
        path: "/analytics",
        title: "Thống kê dữ liệu",
        role: true,
      },
    ],
  },
  {
    key: "/users",
    path: "/users",
    title: "Tài khoản",
    role: true,
    groups: [
      {
        key: "/users/list",
        path: "/users/list",
        title: "Tất cả",
        icon: <UserOutlined />,
        role: true,
      },
      // {
      //   key: "/users/verify",
      //   path: "/users/verify",
      //   title: "Xác minh",
      //   icon: <SafetyOutlined />,
      //   role: "admin",
      // },
      {
        key: "/users/agency",
        path: "/users/agency",
        title: "Đại lý Tổng",
        icon: <TeamOutlined />,
        role: "admin",
      },
      {
        key: "/users/sale",
        path: "/users/sale",
        title: "Nhân viên Sale",
        icon: <TeamOutlined />,
        role: "agency",
      },
    ],
  },
  {
    key: "/history",
    path: "/history",
    title: "Danh sách lịch sử",
    role: true,
    groups: [
      {
        key: "/history/deposit",
        path: "/history/deposit",
        title: "Nạp tiền",
        icon: <DollarOutlined />,
        role: true,
      },
      {
        key: "/history/withdrawal",
        path: "/history/withdrawal",
        title: "Rút tiền",
        icon: <DollarOutlined />,
        role: true,
      },
      // {
      //   key: "/history/game",
      //   path: "/history/game",
      //   title: "Lịch sử Game",
      //   icon: <SwapOutlined />,
      //   role: true,
      // },
      {
        key: "/history/bet",
        path: "/history/bet",
        title: "Đặt cược",
        icon: <RiseOutlined />,
        role: true,
      },
      // {
      //   key: "/history/exchange",
      //   path: "/history/exchange",
      //   title: "Đổi tiền",
      //   icon: <SwapOutlined />,
      //   role: true,
      // },
      {
        key: "/history/add-money",
        path: "/history/add-money",
        title: "Hệ thống",
        icon: <DollarOutlined />,
        role: "admin",
      },
      // {
      //   key: "/history/lucky",
      //   path: "/history/lucky",
      //   title: "Rút thăm",
      //   icon: <DollarOutlined />,
      //   role: "admin",
      // },
    ],
  },
  {
    key: "/game",
    path: "/game",
    title: "Trò chơi",
    role: "admin",
    groups: [
      // {
      //   key: "/game/game1",
      //   path: "/game/game1",
      //   title: "Nhanh 3",
      //   icon: <TagOutlined />,
      //   role: "admin",
      // },
      {
        key: "/game/game2",
        path: "/game/game2",
        title: "GRAND LISBOA",
        icon: <TagOutlined />,
        role: "admin",
      },
      // {
      //   key: "/game/game3",
      //   path: "/game/game3",
      //   title: "Màu sắc hạnh phúc",
      //   icon: <TagOutlined />,
      //   role: "admin",
      // },
      // {
      //   key: "/game/game4",
      //   path: "/game/game4",
      //   title: "Pk10",
      //   icon: <TagOutlined />,
      //   role: "admin",
      // },
      // {
      //   key: "/game/game5",
      //   path: "/game/game5",
      //   title: "11 Chọn 5",
      //   icon: <TagOutlined />,
      //   role: "admin",
      // },
    ],
  },
  {
    key: "/tool",
    path: "/tool",
    title: "Công cụ",
    role: "admin",
    groups: [
      {
        key: "/tool/money",
        path: "/tool/money",
        title: "Nạp tiền tài khoản",
        icon: <DollarOutlined />,
        role: "admin",
      },
      // {
      //   key: "/tool/bank",
      //   path: "/tool/bank",
      //   title: "Cấu hình ngân hàng",
      //   icon: <BankOutlined />,
      //   role: "admin",
      // },
      // {
      //   key: "/tool/product",
      //   path: "/tool/product",
      //   title: "Cấu hình quà tặng",
      //   icon: <DatabaseFilled />,
      //   role: "admin",
      // },
      // {
      //   key: "/tool/notify",
      //   path: "/tool/notify",
      //   title: "Quản lý thông báo",
      //   icon: <NotificationOutlined />,
      //   role: "admin",
      // },
      {
        key: "/tool/setting",
        path: "/tool/setting",
        title: "Cài đặt",
        icon: <SettingOutlined />,
        role: "admin",
      },
    ],
  },
];
